// src/components/social-links.tsx
import classes from './social-links.module.scss';

interface SocialLink {
  name: string;
  link: string;
}

const SocialLinks = () => {
  const socialLinks: SocialLink[] = [
    { name: 'twitter', link: 'https://twitter.com/avivharuzi' },
    {
      name: 'facebook',
      link: 'https://www.facebook.com/people/Aviv-Haruzi/100001590224128',
    },
    { name: 'linkedin', link: 'https://www.linkedin.com/in/avivharuzi' },
    { name: 'instagram', link: 'https://www.instagram.com/avivharuzi' },
    { name: 'github', link: 'https://github.com/avivharuzi' },
    { name: 'envelope', link: 'mailto:avivharuzi@gmail.com' },
  ];

  return (
    <div className={classes.SocialLinks}>
      <ul className="d-flex justify-content-center p-0 m-0">
        {socialLinks.map((socialLink) => {
          return (
            <li className="mx-3" key={socialLink.name}>
              <a
                className={socialLink.name}
                href={socialLink.link}
                target="_blank"
              >
                <i className={'fa fa-' + socialLink.name}></i>
              </a>
            </li>
          );
        })}
      </ul>
    </div>
  );
};

export default SocialLinks;

// src/components/SocialLinks.vue
<template>
  <div class="social-links">
    <ul>
      <li v-for="socialLink in socialLinks" :key="socialLink.name">
        <a class="hvr-grow" :class="socialLink.name" :href="socialLink.link" target="_blank"><i :class="'fa fa-' + socialLink.name"></i></a>
        </li>
    </ul>
  </div>
</template>

<script>
  export default {
    data () {
      return {
        socialLinks: [
          { name: 'twitter', link: 'https://twitter.com/aviv_haruzi' },
          { name: 'facebook', link: 'https://www.facebook.com/aviv.haruzi' },
          { name: 'linkedin', link: 'https://www.linkedin.com/in/aviv-haruzi-33589915b' },
          { name: 'instagram', link: 'https://www.instagram.com/aviv_haruzi' },
          { name: 'github', link: 'https://github.com/avivharuzi' }
        ]
      }
    }
  }
</script>
